In [17]:
import pandas as pd
import geopandas as gpd
import numpy as np

In [6]:
# Load the geometries
runways = gpd.read_file('engage-hackaton/runways.geojson')
thresholds = gpd.read_file('engage-hackaton/thresholds.geojson')

# Load the scenario
scenario = pd.read_parquet('engage-hackaton/samples/sample_scenario_00.parquet')
scenario

,df,squawk,bds60_bds,bds60_heading,bds60_IAS,bds60_Mach,bds60_vrate_barometric,bds60_vrate_inertial,icao24,ts,...,heading,TAS,bds30_bds,bds30_issued_ra,bds30_terminated,bds30_multiple,year,month,day,hour
473055,20,<NA>,60,232.207031,263.0,0.776,-288.0,0.0,344699,1737545255855,...,NaN,NaN,<NA>,<NA>,<NA>,<NA>,2025,1,22,11
473056,21,4516,<NA>,NaN,NaN,NaN,NaN,NaN,407fc1,1737545255855,...,NaN,NaN,<NA>,<NA>,<NA>,<NA>,2025,1,22,11
473057,21,2203,<NA>,NaN,NaN,NaN,NaN,NaN,3964f1,1737545255855,...,NaN,NaN,<NA>,<NA>,<NA>,<NA>,2025,1,22,11
473058,20,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,49514b,1737545255855,...,NaN,NaN,<NA>,<NA>,<NA>,<NA>,2025,1,22,11
473059,21,6012,<NA>,NaN,NaN,NaN,NaN,NaN,344345,1737545255855,...,NaN,NaN,<NA>,<NA>,<NA>,<NA>,2025,1,22,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
679258,17,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,343141,1737545375089,...,NaN,NaN,<NA>,<NA>,<NA>,<NA>,2025,1,22,11
679259,17,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,3991e2,1737545375089,...,NaN,NaN,<NA>,<NA>,<NA>,<NA>,2025,1,22,11
679260,17,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,346384,1737545375089,...,NaN,NaN,<NA>,<NA>,<NA>,<NA>,2025,1,22,11
679261,17,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,346555,1737545375089,...,NaN,NaN,<NA>,<NA>,<NA>,<NA>,2025,1,22,11
679262,17,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,34754c,1737545375089,...,NaN,NaN,<NA>,<NA>,<NA>,<NA>,2025,1,22,11

In [30]:
scenario.groupby("icao24").head()

,df,squawk,bds60_bds,bds60_heading,bds60_IAS,bds60_Mach,bds60_vrate_barometric,bds60_vrate_inertial,icao24,ts,...,heading,TAS,bds30_bds,bds30_issued_ra,bds30_terminated,bds30_multiple,year,month,day,hour
473055,20,<NA>,60,232.207031,263.0,0.776,-288.0,0.0,344699,1737545255855,...,NaN,NaN,<NA>,<NA>,<NA>,<NA>,2025,1,22,11
473056,21,4516,<NA>,NaN,NaN,NaN,NaN,NaN,407fc1,1737545255855,...,NaN,NaN,<NA>,<NA>,<NA>,<NA>,2025,1,22,11
473057,21,2203,<NA>,NaN,NaN,NaN,NaN,NaN,3964f1,1737545255855,...,NaN,NaN,<NA>,<NA>,<NA>,<NA>,2025,1,22,11
473058,20,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,49514b,1737545255855,...,NaN,NaN,<NA>,<NA>,<NA>,<NA>,2025,1,22,11
473059,21,6012,<NA>,NaN,NaN,NaN,NaN,NaN,344345,1737545255855,...,NaN,NaN,<NA>,<NA>,<NA>,<NA>,2025,1,22,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
630507,21,4042,60,233.437500,253.0,0.784,64.0,0.0,4cadc2,1737545260143,...,NaN,NaN,<NA>,<NA>,<NA>,<NA>,2025,1,22,11
633071,18,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,341358,1737545334781,...,NaN,NaN,<NA>,<NA>,<NA>,<NA>,2025,1,22,11
652348,17,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,bce29d,1737545259772,...,NaN,NaN,<NA>,<NA>,<NA>,<NA>,2025,1,22,11
675595,17,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,43ea72,1737545281537,...,NaN,NaN,<NA>,<NA>,<NA>,<NA>,2025,1,22,11
675999,18,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,344511,1737545292596,...,NaN,NaN,<NA>,<NA>,<NA>,<NA>,2025,1,22,11

In [9]:
print(scenario.columns.tolist())

['df', 'squawk', 'bds60_bds', 'bds60_heading', 'bds60_IAS', 'bds60_Mach', 'bds60_vrate_barometric', 'bds60_vrate_inertial', 'icao24', 'ts', 'bds', 'tc', 'NUCp', 'NICb', 'altitude', 'source', 'parity', 'lat_cpr', 'lon_cpr', 'lat_deg', 'lon_deg', 'bds40_bds', 'bds40_selected_mcp', 'bds40_barometric_setting', 'bds50_bds', 'bds50_roll', 'bds50_track', 'bds50_groundspeed', 'bds50_track_rate', 'bds50_TAS', 'bds40_selected_fms', 'NACv', 'groundspeed', 'track', 'vrate_src', 'vertical_rate', 'geo_minus_baro', 'selected_altitude', 'barometric_setting', 'selected_heading', 'NACp', 'tcas_operational', 'tisb', 'id', 'wake_vortex', 'callsign', 'subtype', 'emergency_state', 'version', 'NICa', 'GVA', 'SIL', 'BAI', 'HRD', 'SILs', 'bds45_bds', 'bds45_turbulence', 'bds45_wind_shear', 'bds45_microburst', 'bds45_icing', 'bds45_wake_vortex', 'bds45_static_temperature', 'bds45_static_pressure', 'bds45_radio_height', 'TAH', 'bds40_target_source', 'bds20_bds', 'bds20_callsign', 'bds05_tc', 'bds05_NUCp', 'bds05_NICb', 'bds05_altitude', 'bds05_source', 'bds05_parity', 'bds05_lat_cpr', 'bds05_lon_cpr', 'autopilot', 'vnav_mode', 'alt_hold', 'approach_mode', 'lnav_mode', 'bds10_bds', 'bds10_config', 'bds10_ovc', 'bds10_acas', 'bds10_subnet', 'bds10_level5', 'bds10_mode_s', 'bds10_identification', 'bds10_squitter', 'bds10_sic', 'bds10_gicb', 'bds10_acas_hybrid', 'bds10_acas_ra', 'bds10_dte', 'bds17_bds', 'bds17_bds05', 'bds17_bds06', 'bds17_bds07', 'bds17_bds08', 'bds17_bds09', 'bds17_bds0a', 'bds17_bds20', 'bds17_bds40', 'bds17_bds50', 'bds17_bds5f', 'bds17_bds60', 'bds44_bds', 'bds44_wind_speed', 'bds44_wind_direction', 'bds44_temperature', 'bds44_pressure', 'bds44_turbulence', 'bds44_humidity', 'bds17_bds21', 'bds17_bds51', 'bds17_bds52', 'bds17_bds53', 'bds17_bds41', 'bds17_bds42', 'bds17_bds44', 'bds17_bds48', 'bds21_bds', 'bds21_registration', 'NICs', 'BAQ', 'bds17_bds45', 'bds18_bds', 'bds18_bds30', 'bds18_bds21', 'bds18_bds20', 'bds18_bds1c', 'bds18_bds19', 'bds18_bds18', 'bds18_bds17', 'bds18_bds10', 'bds18_bds0a', 'bds18_bds09', 'bds18_bds08', 'bds18_bds07', 'bds18_bds06', 'bds18_bds05', 'bds19_bds', 'bds19_bds65', 'bds19_bds62', 'bds19_bds61', 'bds19_bds60', 'bds19_bds5f', 'bds19_bds52', 'bds19_bds51', 'bds19_bds50', 'bds19_bds40', 'heading', 'TAS', 'bds30_bds', 'bds30_issued_ra', 'bds30_terminated', 'bds30_multiple', 'year', 'month', 'day', 'hour']

In [10]:
len(scenario.columns.tolist())

162

In [22]:
trainnig_data_header = ['df', 'squawk', 'bds60_bds', 'bds60_heading', 'bds60_IAS', 'bds60_Mach', 'bds60_vrate_barometric', 'bds60_vrate_inertial', 'icao24', 'ts', 'bds', 'NACv', 'groundspeed', 'track', 'vrate_src', 'vertical_rate', 'geo_minus_baro', 'tc', 'NUCp', 'parity', 'lat_cpr', 'lon_cpr', 'lat_deg', 'lon_deg', 'tisb', 'id', 'wake_vortex', 'callsign', 'altitude', 'bds40_bds', 'bds40_selected_mcp', 'bds40_selected_fms', 'bds40_barometric_setting', 'bds50_bds', 'bds50_roll', 'bds50_track', 'bds50_groundspeed', 'bds50_track_rate', 'bds50_TAS', 'version', 'NICa', 'NACp', 'SIL', 'TAH', 'HRD', 'SILs', 'source', 'selected_altitude', 'barometric_setting', 'selected_heading', 'autopilot', 'vnav_mode', 'alt_hold', 'approach_mode', 'tcas_operational', 'lnav_mode', 'GVA', 'BAI', 'subtype', 'emergency_state', 'bds45_bds', 'bds45_turbulence', 'bds45_wind_shear', 'bds45_microburst', 'bds45_icing', 'bds45_wake_vortex', 'bds45_static_temperature', 'bds45_static_pressure', 'bds45_radio_height', 'NICb', 'bds17_bds', 'bds17_bds06', 'bds17_bds07', 'bds17_bds09', 'bds17_bds20', 'bds17_bds41', 'bds17_bds42', 'bds17_bds44', 'bds17_bds48', 'bds17_bds50', 'bds17_bds51', 'bds44_bds', 'bds44_wind_speed', 'bds44_wind_direction', 'bds44_temperature', 'bds44_pressure', 'bds44_turbulence', 'bds44_humidity', 'bds20_bds', 'bds20_callsign', 'bds17_bds05', 'bds17_bds08', 'bds17_bds0a', 'bds17_bds40', 'bds17_bds5f', 'bds17_bds60', 'bds17_bds21', 'bds17_bds43', 'bds17_bds52', 'bds10_bds', 'bds10_config', 'bds10_ovc', 'bds10_acas', 'bds10_subnet', 'bds10_level5', 'bds10_mode_s', 'bds10_identification', 'bds10_squitter', 'bds10_sic', 'bds10_gicb', 'bds10_acas_hybrid', 'bds10_acas_ra', 'bds10_dte', 'bds05_tc', 'bds05_NUCp', 'bds05_NICb', 'bds05_altitude', 'bds05_source', 'bds05_parity', 'bds05_lat_cpr', 'bds05_lon_cpr', 'bds40_target_source', 'bds21_bds', 'bds21_registration', 'bds17_bds53']

In [21]:
trainnig_data_header == scenario.columns.tolist()

False

In [23]:
all_headers = trainnig_data_header + scenario.columns.tolist()

In [25]:
all_headers

['df',
 'squawk',
 'bds60_bds',
 'bds60_heading',
 'bds60_IAS',
 'bds60_Mach',
 'bds60_vrate_barometric',
 'bds60_vrate_inertial',
 'icao24',
 'ts',
 'bds',
 'NACv',
 'groundspeed',
 'track',
 'vrate_src',
 'vertical_rate',
 'geo_minus_baro',
 'tc',
 'NUCp',
 'parity',
 'lat_cpr',
 'lon_cpr',
 'lat_deg',
 'lon_deg',
 'tisb',
 'id',
 'wake_vortex',
 'callsign',
 'altitude',
 'bds40_bds',
 'bds40_selected_mcp',
 'bds40_selected_fms',
 'bds40_barometric_setting',
 'bds50_bds',
 'bds50_roll',
 'bds50_track',
 'bds50_groundspeed',
 'bds50_track_rate',
 'bds50_TAS',
 'version',
 'NICa',
 'NACp',
 'SIL',
 'TAH',
 'HRD',
 'SILs',
 'source',
 'selected_altitude',
 'barometric_setting',
 'selected_heading',
 'autopilot',
 'vnav_mode',
 'alt_hold',
 'approach_mode',
 'tcas_operational',
 'lnav_mode',
 'GVA',
 'BAI',
 'subtype',
 'emergency_state',
 'bds45_bds',
 'bds45_turbulence',
 'bds45_wind_shear',
 'bds45_microburst',
 'bds45_icing',
 'bds45_wake_vortex',
 'bds45_static_temperature',
 'bds45_static_pressure',
 'bds45_radio_height',
 'NICb',
 'bds17_bds',
 'bds17_bds06',
 'bds17_bds07',
 'bds17_bds09',
 'bds17_bds20',
 'bds17_bds41',
 'bds17_bds42',
 'bds17_bds44',
 'bds17_bds48',
 'bds17_bds50',
 'bds17_bds51',
 'bds44_bds',
 'bds44_wind_speed',
 'bds44_wind_direction',
 'bds44_temperature',
 'bds44_pressure',
 'bds44_turbulence',
 'bds44_humidity',
 'bds20_bds',
 'bds20_callsign',
 'bds17_bds05',
 'bds17_bds08',
 'bds17_bds0a',
 'bds17_bds40',
 'bds17_bds5f',
 'bds17_bds60',
 'bds17_bds21',
 'bds17_bds43',
 'bds17_bds52',
 'bds10_bds',
 'bds10_config',
 'bds10_ovc',
 'bds10_acas',
 'bds10_subnet',
 'bds10_level5',
 'bds10_mode_s',
 'bds10_identification',
 'bds10_squitter',
 'bds10_sic',
 'bds10_gicb',
 'bds10_acas_hybrid',
 'bds10_acas_ra',
 'bds10_dte',
 'bds05_tc',
 'bds05_NUCp',
 'bds05_NICb',
 'bds05_altitude',
 'bds05_source',
 'bds05_parity',
 'bds05_lat_cpr',
 'bds05_lon_cpr',
 'bds40_target_source',
 'bds21_bds',
 'bds21_registration',
 'bds17_bds53',
 'df',
 'squawk',
 'bds60_bds',
 'bds60_heading',
 'bds60_IAS',
 'bds60_Mach',
 'bds60_vrate_barometric',
 'bds60_vrate_inertial',
 'icao24',
 'ts',
 'bds',
 'tc',
 'NUCp',
 'NICb',
 'altitude',
 'source',
 'parity',
 'lat_cpr',
 'lon_cpr',
 'lat_deg',
 'lon_deg',
 'bds40_bds',
 'bds40_selected_mcp',
 'bds40_barometric_setting',
 'bds50_bds',
 'bds50_roll',
 'bds50_track',
 'bds50_groundspeed',
 'bds50_track_rate',
 'bds50_TAS',
 'bds40_selected_fms',
 'NACv',
 'groundspeed',
 'track',
 'vrate_src',
 'vertical_rate',
 'geo_minus_baro',
 'selected_altitude',
 'barometric_setting',
 'selected_heading',
 'NACp',
 'tcas_operational',
 'tisb',
 'id',
 'wake_vortex',
 'callsign',
 'subtype',
 'emergency_state',
 'version',
 'NICa',
 'GVA',
 'SIL',
 'BAI',
 'HRD',
 'SILs',
 'bds45_bds',
 'bds45_turbulence',
 'bds45_wind_shear',
 'bds45_microburst',
 'bds45_icing',
 'bds45_wake_vortex',
 'bds45_static_temperature',
 'bds45_static_pressure',
 'bds45_radio_height',
 'TAH',
 'bds40_target_source',
 'bds20_bds',
 'bds20_callsign',
 'bds05_tc',
 'bds05_NUCp',
 'bds05_NICb',
 'bds05_altitude',
 'bds05_source',
 'bds05_parity',
 'bds05_lat_cpr',
 'bds05_lon_cpr',
 'autopilot',
 'vnav_mode',
 'alt_hold',
 'approach_mode',
 'lnav_mode',
 'bds10_bds',
 'bds10_config',
 'bds10_ovc',
 'bds10_acas',
 'bds10_subnet',
 'bds10_level5',
 'bds10_mode_s',
 'bds10_identification',
 'bds10_squitter',
 'bds10_sic',
 'bds10_gicb',
 'bds10_acas_hybrid',
 'bds10_acas_ra',
 'bds10_dte',
 'bds17_bds',
 'bds17_bds05',
 'bds17_bds06',
 'bds17_bds07',
 'bds17_bds08',
 'bds17_bds09',
 'bds17_bds0a',
 'bds17_bds20',
 'bds17_bds40',
 'bds17_bds50',
 'bds17_bds5f',
 'bds17_bds60',
 'bds44_bds',
 'bds44_wind_speed',
 'bds44_wind_direction',
 'bds44_temperature',
 'bds44_pressure',
 'bds44_turbulence',
 'bds44_humidity',
 'bds17_bds21',
 'bds17_bds51',
 'bds17_bds52',
 'bds17_bds53',
 'bds17_bds41',
 'bds17_bds42',
 'bds17_bds44',
 'bds17_bds48',
 'bds21_bds',
 'bds21_registration',
 'NICs',
 'BAQ',
 'bds17_bds45',
 'bds18_bds',
 'bds18_bds30',
 'bds18_bds21',
 'bds18_bds20',
 'bds18_bds1c',
 'bds18_bds19',
 'bds18_bds18',
 'bds18_bds17',
 'bds18_bds10',
 'bds18_bds0a',
 'bds18_bds09',
 'bds18_bds08',
 'bds18_bds07',
 'bds18_bds06',
 'bds18_bds05',
 'bds19_bds',
 'bds19_bds65',
 'bds19_bds62',
 'bds19_bds61',
 'bds19_bds60',
 'bds19_bds5f',
 'bds19_bds52',
 'bds19_bds51',
 'bds19_bds50',
 'bds19_bds40',
 'heading',
 'TAS',
 'bds30_bds',
 'bds30_issued_ra',
 'bds30_terminated',
 'bds30_multiple',
 'year',
 'month',
 'day',
 'hour']

In [28]:
np.unique(all_headers)
len(all_headers)

287